### ISSUE TITLE
Include E2E testing to CI pipeline

### ISSUE THREAD

**Issue by koushikmohan1996** [jobtriage/jobtriage#101]

**Comment by saw-jan** [comment]
you mean include setup for e2e tests in travis yml?

**Comment by koushikmohan1996** [comment]
@saw-jan Yes. Currently, e2e test is available only for signups. Need to add some more important flow like add job application, time logs, etc and  to include them to travis

**Comment by saw-jan** [comment]
yeah. we will shortly make a PR of travis config for e2e tests. And also some more e2e tests in few days.

**Comment by koushikmohan1996** [comment]
> yeah. we will shortly make a PR of travis config for e2e tests. And also some more e2e tests in few days.

Thank you so much :)
