### ISSUE TITLE
Issue in login in Chrome Beta Browser Version - 83.0.4103.14

### ISSUE THREAD

**Issue by gokul-prog** [jobtriage/jobtriage#104]
After login Getting a error page in chrome browser, even after verifying the mail Address.

The issue is not reproduced in different browser such as Edge.

![image](https://user-images.githubusercontent.com/55320340/79745111-3423a000-8325-11ea-91bf-383943fa9e4d.png)

- [x] I have searched the [issues](https://github.com/jobtriage/jobtriage/issues) of this repository and believe that this is not a duplicate.
- [x] This is not a security vulnerability issue

## Current Behavior 😯
Login Failed

## Expected Behavior 🤔
Should have logged in to the app

## Steps to Reproduce 🕹

Steps:

1. 2. 3. 4.

**Comment by koushikmohan1996** [comment]
@gokul-prog Thanks will check

**Comment by koushikmohan1996** [comment]
@all-contributors add @gokul-prog  for bug

**Comment by koushikmohan1996** [comment]
@gokul-prog Can you try now?

**Comment by gokul-prog** [comment]
@koushikmohan1996  Issue is fixed! UI looks great!

**Comment by koushikmohan1996** [comment]
Thanks :)
