### ISSUE TITLE
Email Confirmation Page on Refresh

### ISSUE THREAD

**Issue by arjungrylls** [jobtriage/jobtriage#113]
After successful login to jobtriage 

Apply refresh on any page -  application displays email reconfirmation screen momentarily and loads the required page.  

![Screenshot from 2020-05-15 00-41-19](https://user-images.githubusercontent.com/15036503/81975985-7cdd2900-9645-11ea-97ec-fb668e2e9819.png)

**Comment by arjungrylls** [comment]
@koushikmohan1996   - treat this with high priority

**Comment by koushikmohan1996** [comment]
@arjungrylls Thanks will fix this by this weekend

**Comment by koushikmohan1996** [comment]
#95 Will fix this automatically
