### ISSUE TITLE
[Acceptance Test] Add delete-user API

### ISSUE THREAD

**Issue by saw-jan** [jobtriage/jobtriage#121]
Need to delete user after all the tests have been finished.

**Comment by koushikmohan1996** [comment]
@saw-jan Thanks, will add it. :)

**Comment by koushikmohan1996** [comment]
@all-contributors add @saw-jan for bug

**Comment by saw-jan** [comment]
@koushikmohan1996  We are using delete API that we have created locally. But will pull if you add.

**Comment by koushikmohan1996** [comment]
If it works, you can raise a PR :)

**Comment by koushikmohan1996** [comment]
Fixed inn #126
