### ISSUE TITLE
MailHog as mail server for e2e acceptance tests

### ISSUE THREAD

**Issue by kiranparajuli589** [jobtriage/jobtriage#127]
- [x] I have searched the [issues](https://github.com/jobtriage/jobtriage/issues) of this repository and believe that this is not a duplicate.

## Summary 💡

Jobtriage uses SendMail services while registering a new user. For the production environment, SMTP Gmail setup is used which is nice. But for the test environment, the same email server setup is not appropriate with the number of reasons like:
- No, any registered email address is used while testing.
- Reveals our accounts credentials
- During tests, email is sent to different accounts from the same account, which might be tracked as a spammer or some bots.

## Appropriate Solution
Mailhog can be a solution with a simple configuration and good performance.
Local servers can be created easily with docker commands. The mails that are sent or received can be easily fetched with MailHog rest API.

## Examples 🌈
- Start mailhog with
```
docker run -d -p 1025:1025 -p 8025:8025 mailhog/mailhog
```
Now you can use webUI for mailhog at `http://localhost:8025`
- Send a message using webUI
- Now get the message as:
```
curl http://localhost:1025/api/v1/messages | jq
```
[Documentation URL](https://github.com/mailhog/MailHog/tree/master/docs)

## Motivation 🔦

Better test infrastructure.

**Comment by koushikmohan1996** [comment]
@kiranparajuli589 For test setup, email will not be sent. And the account will be verified by default. Also, the account details is not checked into the code base
