### ISSUE TITLE
Successful signup doesn't redirect to dashboard

### ISSUE THREAD

**Issue by bibekthapa619** [jobtriage/jobtriage#134]
- [x] I have searched the [issues](https://github.com/jobtriage/jobtriage/issues) of this repository and believe that this is not a duplicate.
- [x] This is not a security vulnerability issue

## Current Behavior 😯

After successful signup, user is not directed to dashboard. Dashboard keeps on loading continuously.

## Expected Behavior 🤔

User should be shown dashboard page.

## Steps to Reproduce 🕹

Steps:

1. Signup a user

## Context 🔦

We are currently working on webUI acceptance test for your project. Some tests failed due to this issue after recent changes.

**Comment by koushikmohan1996** [comment]
Thank you so much for raising the issue,  will fix this soon

**Comment by koushikmohan1996** [comment]
@all-contributors add @bibekthapa619  for bug
