### ISSUE TITLE
Trying to sign up with already registered email doesn't throw error but redirects to loading dashboard

### ISSUE THREAD

**Issue by saw-jan** [jobtriage/jobtriage#135]
- [x] I have searched the [issues](https://github.com/jobtriage/jobtriage/issues) of this repository and believe that this is not a duplicate.
- [x] This is not a security vulnerability issue

## Current Behavior 😯
When trying to register with already registered email,
I am redirected to dashboard [ infinite loading dashboard ]. 

## Expected Behavior 🤔
When trying to register with already registered email,
an error message should be displayed
and should not redirect to dashboard

## Steps to Reproduce 🕹

Try sign up with already registered email

**Comment by koushikmohan1996** [comment]
@saw-jan Thanks for raising the issue. I will check this soon.

**Comment by koushikmohan1996** [comment]
@saw-jan I reverted this to old change, but the error message is not proper now, Will fix it soon
