### ISSUE TITLE
Need to Write Tests for Front-End 

### ISSUE THREAD

**Issue by koushikmohan1996** [jobtriage/jobtriage#14]

**Comment by JesusELuna** [comment]
I will be working on it.

**Comment by koushikmohan1996** [comment]
Wow. Really appreciate it :)

**Comment by koushikmohan1996** [comment]
Can you also share your basic idea?

**Comment by JesusELuna** [comment]
@koushikmohan1996 i was thinking in dom testing with [jest](https://jestjs.io/docs/en/tutorial-react)

**Comment by koushikmohan1996** [comment]
> @koushikmohan1996 i was thinking in dom testing with [jest](https://jestjs.io/docs/en/tutorial-react)

Yes seems fine

**Comment by koushikmohan1996** [comment]
Most of the tests are now captured in E2E test so closing this
