### ISSUE TITLE
Alignment Broken in Dashboard Page 

### ISSUE THREAD

**Issue by arjungrylls** [jobtriage/jobtriage#154]
# CSS Alignment Broken in Dashboard Page 

  Issue reproducible in Windows OS Chrome Browser

![image](https://user-images.githubusercontent.com/15036503/86200362-102cd800-bb7a-11ea-9549-828bcb37230e.png)

**Comment by arjungrylls** [comment]
Dashboard should render without horizontal scroll bar.

**Comment by koushikmohan1996** [comment]
@arjungrylls This will happen if the window is small. Can't accommodate all the panes in small window

**Comment by arjungrylls** [comment]
closing this for now but need to fix the aligment as it is not consistent across browsers of same screen size
