### ISSUE TITLE
Implement APIs for Forgot & Change Password

### ISSUE THREAD

**Issue by koushikmohan1996** [jobtriage/jobtriage#23]

**Comment by AyoAlfonso** [comment]
Working on this.

**Comment by koushikmohan1996** [comment]
@AyoAlfonso Awesome! Thanks :) 
If you need any help setting up the server or if you want to discuss any ideas, feel free to ask here :)

**Comment by koushikmohan1996** [comment]
@AyoAlfonso Are you still working on this? If you face any issues please let me know!

**Comment by koushikmohan1996** [comment]
I will be working on this
