### ISSUE TITLE
[Dashboard]: Spacing and Alignment of Sidebar

### ISSUE THREAD

**Issue by yashpandit** [jobtriage/jobtriage#28]
The alignment and spacing in the sidebar are off as the text "Application" is overflowing. See GIF below.
![dashboard-issue](https://user-images.githubusercontent.com/26370910/75137274-35619380-570d-11ea-8c6e-16addc496b86.gif)

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/jobtriage/jobtriage/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The text in the sidebar is overflowing. So the UI is not looking consistent.

## Expected Behavior 🤔

After fixing the issue, the spacing, and alignment should look consistent and the Menu text should not overflow.

## Steps to Reproduce 🕹

Steps:

1. Login to JobTriage from the Home/Landing Page
2. You will be navigated to the Dashboard.
3. Look at the sidebar for the issue.

**Comment by koushikmohan1996** [comment]
Fixed in #69
