### ISSUE TITLE
[Dashboard]: Add Job Button Should Be Fixed on Screen

### ISSUE THREAD

**Issue by yashpandit** [jobtriage/jobtriage#29]
Add Job Button on the Dashboard should be at the fixed position(bottom right) and should not move with the horizontal scroll.

- [x] The issue is present in the latest release.
- [x] I have searched the [issues](https://github.com/jobtriage/jobtriage/issues) of this repository and believe that this is not a duplicate.

## Current Behavior 😯

The Add button is moving with the scroll bar

## Expected Behavior 🤔

The Add button should not move with the scroll bar

## Steps to Reproduce 🕹

Steps:

1. Login to JobTriage from the Home/Landing Page.
2. You will be navigated to the Dashboard.
3. Look at the Add button and scroll horizontally.

**Comment by koushikmohan1996** [comment]
Fixed in #56
