### ISSUE TITLE
Google font is loading multiple times

### ISSUE THREAD

**Issue by koushikmohan1996** [jobtriage/jobtriage#79]
![image](https://user-images.githubusercontent.com/24666922/78042472-aab92780-738f-11ea-9fc0-f02bbfebeef4.png)

**Comment by JesusELuna** [comment]
Hi!
I will be working on it.

**Comment by koushikmohan1996** [comment]
@JesusELuna Awesome. Thanks :)

If you need any help setting up dev environment. Let me know!
